var datasetDict = {
    "order_to_repair_vacate_orders":
        {
            "groupby_count":["a.ntacode","b.ntaname"],	
            "groupby_cat":"primary_vacate_reason",
            "first_cat":"Fire Damage",
            "datename":"vacate_effective_date",
            "name":'Order to Repair or Vacate',
            "count":"Neighborhood Count",
            "perpop":"Density by Population"
        },
    "threeoneone_2010_2018":
        {
            "groupby_cat":"complaint_type",
            "first_cat":"Blocked Driveway",
            "name":"311 Complaints",
            "count":"Neighborhood Count",
            "datename":"created_date"
        },
    "yellow_cab_pickup_nta":
        {
            "groupby_cat":"no",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"cartodb_id",
            "name":"Yellow Cab Pickups",
            "count":"Neighborhood Count",
            "datename":"trip_picku"
        },
    "liquor_licences_withnta":
        {
            "groupby_cat":"license_ty",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"GROCERY STORE BEER",
            "name":"Liquor Licenses",
            "count":"Neighborhood Count",
            "datename":"license_ef"
        },
    "geocode_health_inspections":
        {
            "groupby_cat":"cuisine_description",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"American",
            "name":"Restaurant Health Inspections (2017)",
            "count":"Neighborhood Count",
            "datename":"inspection_date"
        },
    "nyc_dog_licensing_dataset":
        {
            "groupby_cat":"breedname",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Beagle",
            "name":"Dog Licenses (2017)",
            "count":"Neighborhood Count",
            "datename":"licenseissueddate"
        },
    "nta_acs_age_sex":
        {
            "groupby_cat":"none",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Total",
            "name":"ACS Age & Sex",
            "count":"Neighborhood Count",
            "datename":"None"
        },
    "nta_acs_demo":
        {
            "groupby_cat":"none",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Total",
            "name":"ACS Demographics",
            "count":"Neighborhood Count",
            "datename":"None"
        },
    }

var allNTA={"Airport": "QN98",
"Allerton-Pelham Gardens": "BX31",
"Annadale-Huguenot-Prince's Bay-Eltingville": "SI01",
"Arden Heights": "SI48",
"Astoria": "QN70",
"Auburndale": "QN48",
"Baisley Park": "QN76",
"Bath Beach": "BK27",
"Battery Park City-Lower Manhattan": "MN25",
"Bay Ridge": "BK31",
"Bayside-Bayside Hills": "QN46",
"Bedford": "BK75",
"Bedford Park-Fordham North": "BX05",
"Bellerose": "QN43",
"Belmont": "BX06",
"Bensonhurst East": "BK29",
"Bensonhurst West": "BK28",
"Borough Park": "BK88",
"Breezy Point-Belle Harbor-Rockaway Park-Broad Channel": "QN10",
"Briarwood-Jamaica Hills": "QN35",
"Brighton Beach": "BK19",
"Bronxdale": "BX07",
"Brooklyn Heights-Cobble Hill": "BK09",
"Brownsville": "BK81",
"Bushwick North": "BK77",
"Bushwick South": "BK78",
"Cambria Heights": "QN33",
"Canarsie": "BK50",
"Carroll Gardens-Columbia Street-Red Hook": "BK33",
"Central Harlem North-Polo Grounds": "MN03",
"Central Harlem South": "MN11",
"Charleston-Richmond Valley-Tottenville": "SI11",
"Chinatown": "MN27",
"Claremont-Bathgate": "BX01",
"Clinton": "MN15",
"Clinton Hill": "BK69",
"Co-op City": "BX13",
"College Point": "QN23",
"Corona": "QN25",
"Crotona Park East": "BX75",
"Crown Heights North": "BK61",
"Crown Heights South": "BK63",
"Cypress Hills-City Line": "BK83",
"DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill": "BK38",
"Douglas Manor-Douglaston-Little Neck": "QN45",
"Dyker Heights": "BK30",
"East Concourse-Concourse Village": "BX14",
"East Elmhurst": "QN27",
"East Flatbush-Farragut": "BK91",
"East Flushing": "QN52",
"East Harlem North": "MN34",
"East Harlem South": "MN33",
"East New York": "BK82",
"East New York (Pennsylvania Ave)": "BK85",
"East Tremont": "BX17",
"East Village": "MN22",
"East Williamsburg": "BK90",
"Eastchester-Edenwald-Baychester": "BX03",
"Elmhurst": "QN29",
"Elmhurst-Maspeth": "QN50",
"Erasmus": "BK95",
"Far Rockaway-Bayswater": "QN15",
"Flatbush": "BK42",
"Flatlands": "BK58",
"Flushing": "QN22",
"Fordham South": "BX40",
"Forest Hills": "QN17",
"Fort Greene": "BK68",
"Fresh Meadows-Utopia": "QN41",
"Ft. Totten-Bay Terrace-Clearview": "QN47",
"Georgetown-Marine Park-Bergen Beach-Mill Basin": "BK45",
"Glen Oaks-Floral Park-New Hyde Park": "QN44",
"Glendale": "QN19",
"Gramercy": "MN21",
"Grasmere-Arrochar-Ft. Wadsworth": "SI14",
"Gravesend": "BK26",
"Great Kills": "SI54",
"Greenpoint": "BK76",
"Grymes Hill-Clifton-Fox Hills": "SI08",
"Hamilton Heights": "MN04",
"Hammels-Arverne-Edgemere": "QN12",
"Highbridge": "BX26",
"Hollis": "QN07",
"Homecrest": "BK25",
"Hudson Yards-Chelsea-Flatiron-Union Square": "MN13",
"Hunters Point-Sunnyside-West Maspeth": "QN31",
"Hunts Point": "BX27",
"Jackson Heights": "QN28",
"Jamaica": "QN61",
"Jamaica Estates-Holliswood": "QN06",
"Kensington-Ocean Parkway": "BK41",
"Kew Gardens": "QN60",
"Kew Gardens Hills": "QN37",
"Kingsbridge Heights": "BX30",
"Laurelton": "QN66",
"Lenox Hill-Roosevelt Island": "MN31",
"Lincoln Square": "MN14",
"Lindenwood-Howard Beach": "QN57",
"Longwood": "BX33",
"Lower East Side": "MN28",
"Madison": "BK44",
"Manhattanville": "MN06",
"Marble Hill-Inwood": "MN01",
"Mariner's Harbor-Arlington-Port Ivory-Graniteville": "SI12",
"Maspeth": "QN30",
"Melrose South-Mott Haven North": "BX34",
"Middle Village": "QN21",
"Midtown-Midtown South": "MN17",
"Midwood": "BK43",
"Morningside Heights": "MN09",
"Morrisania-Melrose": "BX35",
"Mott Haven-Port Morris": "BX39",
"Mount Hope": "BX41",
"Murray Hill": "QN51",
"Murray Hill-Kips Bay": "MN20",
"New Brighton-Silver Lake": "SI35",
"New Dorp-Midland Beach": "SI45",
"New Springville-Bloomfield-Travis": "SI05",
"North Corona": "QN26",
"North Riverdale-Fieldston-Riverdale": "BX22",
"North Side-South Side": "BK73",
"Norwood": "BX43",
"Oakland Gardens": "QN42",
"Oakwood-Oakwood Beach": "SI25",
"Ocean Hill": "BK79",
"Ocean Parkway South": "BK46",
"Old Astoria": "QN71",
"Old Town-Dongan Hills-South Beach": "SI36",
"Ozone Park": "QN56",
"Park Slope-Gowanus": "BK37",
"Parkchester": "BX46",
"Pelham Bay-Country Club-City Island": "BX10",
"Pelham Parkway": "BX49",
"Pomonok-Flushing Heights-Hillcrest": "QN38",
"Port Richmond": "SI28",
"Prospect Heights": "BK64",
"Prospect Lefferts Gardens-Wingate": "BK60",
"Queens Village": "QN34",
"Queensboro Hill": "QN62",
"Queensbridge-Ravenswood-Long Island City": "QN68",
"Rego Park": "QN18",
"Richmond Hill": "QN54",
"Ridgewood": "QN20",
"Rikers Island": "BX98",
"Rosedale": "QN05",
"Rossville-Woodrow": "SI32",
"Rugby-Remsen Village": "BK96",
"Schuylerville-Throgs Neck-Edgewater Park": "BX52",
"Seagate-Coney Island": "BK21",
"Sheepshead Bay-Gerritsen Beach-Manhattan Beach": "BK17",
"SoHo-TriBeCa-Civic Center-Little Italy": "MN24",
"Soundview-Bruckner": "BX55",
"Soundview-Castle Hill-Clason Point-Harding Park": "BX09",
"South Jamaica": "QN01",
"South Ozone Park": "QN55",
"Springfield Gardens North": "QN02",
"Springfield Gardens South-Brookville": "QN03",
"Spuyten Duyvil-Kingsbridge": "BX29",
"St. Albans": "QN08",
"Stapleton-Rosebank": "SI37",
"Starrett City": "BK93",
"Steinway": "QN72",
"Stuyvesant Heights": "BK35",
"Stuyvesant Town-Cooper Village": "MN50",
"Sunset Park East": "BK34",
"Sunset Park West": "BK32",
"Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill": "SI24",
"Turtle Bay-East Midtown": "MN19",
"University Heights-Morris Heights": "BX36",
"Upper East Side-Carnegie Hill": "MN40",
"Upper West Side": "MN12",
"Van Cortlandt Village": "BX28",
"Van Nest-Morris Park-Westchester Square": "BX37",
"Washington Heights North": "MN35",
"Washington Heights South": "MN36",
"West Brighton": "BK23",
"West Concourse": "BX63",
"West Farms-Bronx River": "BX08",
"West New Brighton-New Brighton-St. George": "SI22",
"West Village": "MN23",
"Westchester-Unionport": "BX59",
"Westerleigh": "SI07",
"Whitestone": "QN49",
"Williamsbridge-Olinville": "BX44",
"Williamsburg": "BK72",
"Windsor Terrace": "BK40",
"Woodhaven": "QN53",
"Woodlawn-Wakefield": "BX62",
"Woodside": "QN63",
"Yorkville": "MN32",
"park-cemetery-etc-Bronx": "BX99",
"park-cemetery-etc-Brooklyn": "BK99",
"park-cemetery-etc-Manhattan": "MN99",
"park-cemetery-etc-Queens": "QN99",
"park-cemetery-etc-Staten Island": "SI99"}


colorbrewer={'Paired':{9: ["#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f","#ff7f00","#cab2d6"]}}