var datasetDict = {
    "order_to_repair_vacate_orders":
        {
            "groupby_count":["a.ntacode","b.ntaname"],	
            "groupby_cat":"primary_vacate_reason",
            "first_cat":"Total",
            "datename":"vacate_effective_date",
            "name":'Order to Repair or Vacate',
            "count":"Neighborhood Count",
            "perpop":"Density by Population"
        },
    "threeoneone_2010_2018":
        {
            "groupby_cat":"complaint_type",
            "first_cat":"Total",
            "name":"311 Complaints",
            "count":"Neighborhood Count",
            "datename":"created_date"
        },
    // "yellow_cab_pickup_nta":
    //     {
    //         "groupby_cat":"no",
    //         "groupby_count":["a.ntacode","b.ntaname"],	
    //         "first_cat":"Total",
    //         "name":"Yellow Cab Pickups",
    //         "count":"Neighborhood Count",
    //         "datename":"trip_picku"
    //     },
    "liquor_licences_withnta":
        {
            "groupby_cat":"license_ty",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Total",
            "name":"Liquor Licenses",
            "count":"Neighborhood Count",
            "datename":"license_ef"
        },
    "geocode_health_inspections":
        {
            "groupby_cat":"cuisine_description",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Total",
            "name":"Restaurant Health Inspections (2017)",
            "count":"Neighborhood Count",
            "datename":"inspection_date"
        },
    "nyc_dog_licensing_dataset":
        {
            "groupby_cat":"breedname",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Total",
            "name":"Dog Licenses (2017)",
            "count":"Neighborhood Count",
            "datename":"licenseissueddate"
        },
    "nta_acs_age_sex":
        {
            "groupby_cat":"variable",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Total Population",
            "name":"ACS Age & Sex",
            "count":"Neighborhood Count",
            "datename":"year",
            "denom_table":'nta_acs_age_sex',
            "denominator":"total_population"
        },
    "nta_acs_demo":
        {
            "groupby_cat":"variable",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"White alone",
            "name":"ACS Demographics",
            "count":"Neighborhood Count",
            "datename":"year",
            "denom_table":"nta_acs_age_sex",
            "denom":"total_population"
        },
    "nta_acs_income":
        {
            "groupby_cat":"variable",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"$100,000 to $124,999",
            "name":"ACS Income by Households",
            "count":"Neighborhood Count",
            "datename":"year",
        },        
    "nta_acs_edu":
        {
            "groupby_cat":"variable",
            "groupby_count":["a.ntacode","b.ntaname"],	
            "first_cat":"Regular high school diploma",
            "name":"ACS Education",
            "count":"Neighborhood Count",
            "datename":"year",
        },        
    }

var allNTA={"Airport": "QN98",
"Allerton-Pelham Gardens": "BX31",
"Annadale-Huguenot-Prince's Bay-Eltingville": "SI01",
"Arden Heights": "SI48",
"Astoria": "QN70",
"Auburndale": "QN48",
"Baisley Park": "QN76",
"Bath Beach": "BK27",
"Battery Park City-Lower Manhattan": "MN25",
"Bay Ridge": "BK31",
"Bayside-Bayside Hills": "QN46",
"Bedford": "BK75",
"Bedford Park-Fordham North": "BX05",
"Bellerose": "QN43",
"Belmont": "BX06",
"Bensonhurst East": "BK29",
"Bensonhurst West": "BK28",
"Borough Park": "BK88",
"Breezy Point-Belle Harbor-Rockaway Park-Broad Channel": "QN10",
"Briarwood-Jamaica Hills": "QN35",
"Brighton Beach": "BK19",
"Bronxdale": "BX07",
"Brooklyn Heights-Cobble Hill": "BK09",
"Brownsville": "BK81",
"Bushwick North": "BK77",
"Bushwick South": "BK78",
"Cambria Heights": "QN33",
"Canarsie": "BK50",
"Carroll Gardens-Columbia Street-Red Hook": "BK33",
"Central Harlem North-Polo Grounds": "MN03",
"Central Harlem South": "MN11",
"Charleston-Richmond Valley-Tottenville": "SI11",
"Chinatown": "MN27",
"Claremont-Bathgate": "BX01",
"Clinton": "MN15",
"Clinton Hill": "BK69",
"Co-op City": "BX13",
"College Point": "QN23",
"Corona": "QN25",
"Crotona Park East": "BX75",
"Crown Heights North": "BK61",
"Crown Heights South": "BK63",
"Cypress Hills-City Line": "BK83",
"DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill": "BK38",
"Douglas Manor-Douglaston-Little Neck": "QN45",
"Dyker Heights": "BK30",
"East Concourse-Concourse Village": "BX14",
"East Elmhurst": "QN27",
"East Flatbush-Farragut": "BK91",
"East Flushing": "QN52",
"East Harlem North": "MN34",
"East Harlem South": "MN33",
"East New York": "BK82",
"East New York (Pennsylvania Ave)": "BK85",
"East Tremont": "BX17",
"East Village": "MN22",
"East Williamsburg": "BK90",
"Eastchester-Edenwald-Baychester": "BX03",
"Elmhurst": "QN29",
"Elmhurst-Maspeth": "QN50",
"Erasmus": "BK95",
"Far Rockaway-Bayswater": "QN15",
"Flatbush": "BK42",
"Flatlands": "BK58",
"Flushing": "QN22",
"Fordham South": "BX40",
"Forest Hills": "QN17",
"Fort Greene": "BK68",
"Fresh Meadows-Utopia": "QN41",
"Ft. Totten-Bay Terrace-Clearview": "QN47",
"Georgetown-Marine Park-Bergen Beach-Mill Basin": "BK45",
"Glen Oaks-Floral Park-New Hyde Park": "QN44",
"Glendale": "QN19",
"Gramercy": "MN21",
"Grasmere-Arrochar-Ft. Wadsworth": "SI14",
"Gravesend": "BK26",
"Great Kills": "SI54",
"Greenpoint": "BK76",
"Grymes Hill-Clifton-Fox Hills": "SI08",
"Hamilton Heights": "MN04",
"Hammels-Arverne-Edgemere": "QN12",
"Highbridge": "BX26",
"Hollis": "QN07",
"Homecrest": "BK25",
"Hudson Yards-Chelsea-Flatiron-Union Square": "MN13",
"Hunters Point-Sunnyside-West Maspeth": "QN31",
"Hunts Point": "BX27",
"Jackson Heights": "QN28",
"Jamaica": "QN61",
"Jamaica Estates-Holliswood": "QN06",
"Kensington-Ocean Parkway": "BK41",
"Kew Gardens": "QN60",
"Kew Gardens Hills": "QN37",
"Kingsbridge Heights": "BX30",
"Laurelton": "QN66",
"Lenox Hill-Roosevelt Island": "MN31",
"Lincoln Square": "MN14",
"Lindenwood-Howard Beach": "QN57",
"Longwood": "BX33",
"Lower East Side": "MN28",
"Madison": "BK44",
"Manhattanville": "MN06",
"Marble Hill-Inwood": "MN01",
"Mariner's Harbor-Arlington-Port Ivory-Graniteville": "SI12",
"Maspeth": "QN30",
"Melrose South-Mott Haven North": "BX34",
"Middle Village": "QN21",
"Midtown-Midtown South": "MN17",
"Midwood": "BK43",
"Morningside Heights": "MN09",
"Morrisania-Melrose": "BX35",
"Mott Haven-Port Morris": "BX39",
"Mount Hope": "BX41",
"Murray Hill": "QN51",
"Murray Hill-Kips Bay": "MN20",
"New Brighton-Silver Lake": "SI35",
"New Dorp-Midland Beach": "SI45",
"New Springville-Bloomfield-Travis": "SI05",
"Entire New York City": "NYC",
"North Corona": "QN26",
"North Riverdale-Fieldston-Riverdale": "BX22",
"North Side-South Side": "BK73",
"Norwood": "BX43",
"Oakland Gardens": "QN42",
"Oakwood-Oakwood Beach": "SI25",
"Ocean Hill": "BK79",
"Ocean Parkway South": "BK46",
"Old Astoria": "QN71",
"Old Town-Dongan Hills-South Beach": "SI36",
"Ozone Park": "QN56",
"Park Slope-Gowanus": "BK37",
"Parkchester": "BX46",
"Pelham Bay-Country Club-City Island": "BX10",
"Pelham Parkway": "BX49",
"Pomonok-Flushing Heights-Hillcrest": "QN38",
"Port Richmond": "SI28",
"Prospect Heights": "BK64",
"Prospect Lefferts Gardens-Wingate": "BK60",
"Queens Village": "QN34",
"Queensboro Hill": "QN62",
"Queensbridge-Ravenswood-Long Island City": "QN68",
"Rego Park": "QN18",
"Richmond Hill": "QN54",
"Ridgewood": "QN20",
"Rikers Island": "BX98",
"Rosedale": "QN05",
"Rossville-Woodrow": "SI32",
"Rugby-Remsen Village": "BK96",
"Schuylerville-Throgs Neck-Edgewater Park": "BX52",
"Seagate-Coney Island": "BK21",
"Sheepshead Bay-Gerritsen Beach-Manhattan Beach": "BK17",
"SoHo-TriBeCa-Civic Center-Little Italy": "MN24",
"Soundview-Bruckner": "BX55",
"Soundview-Castle Hill-Clason Point-Harding Park": "BX09",
"South Jamaica": "QN01",
"South Ozone Park": "QN55",
"Springfield Gardens North": "QN02",
"Springfield Gardens South-Brookville": "QN03",
"Spuyten Duyvil-Kingsbridge": "BX29",
"St. Albans": "QN08",
"Stapleton-Rosebank": "SI37",
"Starrett City": "BK93",
"Steinway": "QN72",
"Stuyvesant Heights": "BK35",
"Stuyvesant Town-Cooper Village": "MN50",
"Sunset Park East": "BK34",
"Sunset Park West": "BK32",
"Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill": "SI24",
"Turtle Bay-East Midtown": "MN19",
"University Heights-Morris Heights": "BX36",
"Upper East Side-Carnegie Hill": "MN40",
"Upper West Side": "MN12",
"Van Cortlandt Village": "BX28",
"Van Nest-Morris Park-Westchester Square": "BX37",
"Washington Heights North": "MN35",
"Washington Heights South": "MN36",
"West Brighton": "BK23",
"West Concourse": "BX63",
"West Farms-Bronx River": "BX08",
"West New Brighton-New Brighton-St. George": "SI22",
"West Village": "MN23",
"Westchester-Unionport": "BX59",
"Westerleigh": "SI07",
"Whitestone": "QN49",
"Williamsbridge-Olinville": "BX44",
"Williamsburg": "BK72",
"Windsor Terrace": "BK40",
"Woodhaven": "QN53",
"Woodlawn-Wakefield": "BX62",
"Woodside": "QN63",
"Yorkville": "MN32",
"park-cemetery-etc-Bronx": "BX99",
"park-cemetery-etc-Brooklyn": "BK99",
"park-cemetery-etc-Manhattan": "MN99",
"park-cemetery-etc-Queens": "QN99",
"park-cemetery-etc-Staten Island": "SI99"}

var reverse_nta_name_lookup = {
    "NYC": "Entire NYC",
    "QN98":"Airport",
    "BX31":"Allerton-Pelham Gardens",
    "SI01":"Annadale-Huguenot-Prince's Bay-Eltingville",
    "SI48":"Arden Heights",
    "QN70":"Astoria",
    "QN48":"Auburndale",
    "QN76":"Baisley Park",
    "BK27":"Bath Beach",
    "MN25":"Battery Park City-Lower Manhattan",
    "BK31":"Bay Ridge",
    "QN46":"Bayside-Bayside Hills",
    "BK75":"Bedford",
    "BX05":"Bedford Park-Fordham North",
    "QN43":"Bellerose",
    "BX06":"Belmont",
    "BK29":"Bensonhurst East",
    "BK28":"Bensonhurst West",
    "BK88":"Borough Park",
    "QN10":"Breezy Point-Belle Harbor-Rockaway Park-Broad Channel",
    "QN35":"Briarwood-Jamaica Hills",
    "BK19":"Brighton Beach",
    "BX07":"Bronxdale",
    "BK09":"Brooklyn Heights-Cobble Hill",
    "BK81":"Brownsville",
    "BK77":"Bushwick North",
    "BK78":"Bushwick South",
    "QN33":"Cambria Heights",
    "BK50":"Canarsie",
    "BK33":"Carroll Gardens-Columbia Street-Red Hook",
    "MN03":"Central Harlem North-Polo Grounds",
    "MN11":"Central Harlem South",
    "SI11":"Charleston-Richmond Valley-Tottenville",
    "MN27":"Chinatown",
    "BX01":"Claremont-Bathgate",
    "MN15":"Clinton",
    "BK69":"Clinton Hill",
    "BX13":"Co-op City",
    "QN23":"College Point",
    "QN25":"Corona",
    "BX75":"Crotona Park East",
    "BK61":"Crown Heights North",
    "BK63":"Crown Heights South",
    "BK83":"Cypress Hills-City Line",
    "BK38":"DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill",
    "QN45":"Douglas Manor-Douglaston-Little Neck",
    "BK30":"Dyker Heights",
    "BX14":"East Concourse-Concourse Village",
    "QN27":"East Elmhurst",
    "BK91":"East Flatbush-Farragut",
    "QN52":"East Flushing",
    "MN34":"East Harlem North",
    "MN33":"East Harlem South",
    "BK82":"East New York",
    "BK85":"East New York (Pennsylvania Ave)",
    "BX17":"East Tremont",
    "MN22":"East Village",
    "BK90":"East Williamsburg",
    "BX03":"Eastchester-Edenwald-Baychester",
    "QN29":"Elmhurst",
    "QN50":"Elmhurst-Maspeth",
    "BK95":"Erasmus",
    "QN15":"Far Rockaway-Bayswater",
    "BK42":"Flatbush",
    "BK58":"Flatlands",
    "QN22":"Flushing",
    "BX40":"Fordham South",
    "QN17":"Forest Hills",
    "BK68":"Fort Greene",
    "QN41":"Fresh Meadows-Utopia",
    "QN47":"Ft. Totten-Bay Terrace-Clearview",
    "BK45":"Georgetown-Marine Park-Bergen Beach-Mill Basin",
    "QN44":"Glen Oaks-Floral Park-New Hyde Park",
    "QN19":"Glendale",
    "MN21":"Gramercy",
    "SI14":"Grasmere-Arrochar-Ft. Wadsworth",
    "BK26":"Gravesend",
    "SI54":"Great Kills",
    "BK76":"Greenpoint",
    "SI08":"Grymes Hill-Clifton-Fox Hills",
    "MN04":"Hamilton Heights",
    "QN12":"Hammels-Arverne-Edgemere",
    "BX26":"Highbridge",
    "QN07":"Hollis",
    "BK25":"Homecrest",
    "MN13":"Hudson Yards-Chelsea-Flatiron-Union Square",
    "QN31":"Hunters Point-Sunnyside-West Maspeth",
    "BX27":"Hunts Point",
    "QN28":"Jackson Heights",
    "QN61":"Jamaica",
    "QN06":"Jamaica Estates-Holliswood",
    "BK41":"Kensington-Ocean Parkway",
    "QN60":"Kew Gardens",
    "QN37":"Kew Gardens Hills",
    "BX30":"Kingsbridge Heights",
    "QN66":"Laurelton",
    "MN31":"Lenox Hill-Roosevelt Island",
    "MN14":"Lincoln Square",
    "QN57":"Lindenwood-Howard Beach",
    "BX33":"Longwood",
    "MN28":"Lower East Side",
    "BK44":"Madison",
    "MN06":"Manhattanville",
    "MN01":"Marble Hill-Inwood",
    "SI12":"Mariner's Harbor-Arlington-Port Ivory-Graniteville",
    "QN30":"Maspeth",
    "BX34":"Melrose South-Mott Haven North",
    "QN21":"Middle Village",
    "MN17":"Midtown-Midtown South",
    "BK43":"Midwood",
    "MN09":"Morningside Heights",
    "BX35":"Morrisania-Melrose",
    "BX39":"Mott Haven-Port Morris",
    "BX41":"Mount Hope",
    "QN51":"Murray Hill",
    "MN20":"Murray Hill-Kips Bay",
    "SI35":"New Brighton-Silver Lake",
    "SI45":"New Dorp-Midland Beach",
    "SI05":"New Springville-Bloomfield-Travis",
    "NYC":"Entire New York City",
    "QN26":"North Corona",
    "BX22":"North Riverdale-Fieldston-Riverdale",
    "BK73":"North Side-South Side",
    "BX43":"Norwood",
    "QN42":"Oakland Gardens",
    "SI25":"Oakwood-Oakwood Beach",
    "BK79":"Ocean Hill",
    "BK46":"Ocean Parkway South",
    "QN71":"Old Astoria",
    "SI36":"Old Town-Dongan Hills-South Beach",
    "QN56":"Ozone Park",
    "BK37":"Park Slope-Gowanus",
    "BX46":"Parkchester",
    "BX10":"Pelham Bay-Country Club-City Island",
    "BX49":"Pelham Parkway",
    "QN38":"Pomonok-Flushing Heights-Hillcrest",
    "SI28":"Port Richmond",
    "BK64":"Prospect Heights",
    "BK60":"Prospect Lefferts Gardens-Wingate",
    "QN34":"Queens Village",
    "QN62":"Queensboro Hill",
    "QN68":"Queensbridge-Ravenswood-Long Island City",
    "QN18":"Rego Park",
    "QN54":"Richmond Hill",
    "QN20":"Ridgewood",
    "BX98":"Rikers Island",
    "QN05":"Rosedale",
    "SI32":"Rossville-Woodrow",
    "BK96":"Rugby-Remsen Village",
    "BX52":"Schuylerville-Throgs Neck-Edgewater Park",
    "BK21":"Seagate-Coney Island",
    "BK17":"Sheepshead Bay-Gerritsen Beach-Manhattan Beach",
    "MN24":"SoHo-TriBeCa-Civic Center-Little Italy",
    "BX55":"Soundview-Bruckner",
    "BX09":"Soundview-Castle Hill-Clason Point-Harding Park",
    "QN01":"South Jamaica",
    "QN55":"South Ozone Park",
    "QN02":"Springfield Gardens North",
    "QN03":"Springfield Gardens South-Brookville",
    "BX29":"Spuyten Duyvil-Kingsbridge",
    "QN08":"St. Albans",
    "SI37":"Stapleton-Rosebank",
    "BK93":"Starrett City",
    "QN72":"Steinway",
    "BK35":"Stuyvesant Heights",
    "MN50":"Stuyvesant Town-Cooper Village",
    "BK34":"Sunset Park East",
    "BK32":"Sunset Park West",
    "SI24":"Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill",
    "MN19":"Turtle Bay-East Midtown",
    "BX36":"University Heights-Morris Heights",
    "MN40":"Upper East Side-Carnegie Hill",
    "MN12":"Upper West Side",
    "BX28":"Van Cortlandt Village",
    "BX37":"Van Nest-Morris Park-Westchester Square",
    "MN35":"Washington Heights North",
    "MN36":"Washington Heights South",
    "BK23":"West Brighton",
    "BX63":"West Concourse",
    "BX08":"West Farms-Bronx River",
    "SI22":"West New Brighton-New Brighton-St. George",
    "MN23":"West Village",
    "BX59":"Westchester-Unionport",
    "SI07":"Westerleigh",
    "QN49":"Whitestone",
    "BX44":"Williamsbridge-Olinville",
    "BK72":"Williamsburg",
    "BK40":"Windsor Terrace",
    "QN53":"Woodhaven",
    "BX62":"Woodlawn-Wakefield",
    "QN63":"Woodside",
    "MN32":"Yorkville",
    "BX99":"park-cemetery-etc-Bronx",
    "BK99":"park-cemetery-etc-Brooklyn",
    "MN99":"park-cemetery-etc-Manhattan",
    "QN99":"park-cemetery-etc-Queens",
    "SI99":"park-cemetery-etc-Staten Island"}

colorbrewer={'Paired':{9: ["#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f","#ff7f00","#cab2d6"]}}

var acs_table_sql=```
SELECT * from nta_acs_demo as a
WHERE ntacode in (${ntaList})
```

var other_table_sql=```
SELECT a.*,
	   to_char(cast(a.count_per_type as decimal)/b.count_nta*100,'999D99%25') type_percentage,
       b.count_nta FROM
			(SELECT * FROM
				(SELECT a.*,
						rank() OVER (PARTITION BY ntacode ORDER BY count_per_type DESC ) as rank
				FROM (SELECT a.ntacode,
							  b.ntaname,
							  a.${datasetDict[dataset]['groupby_cat']},
							  count(*) count_per_type,
							  to_char(count(*)/b.population_2016*100,'999D99%25') as perpop
						FROM  "wxu-carto".${dataset} as a, "wxu-carto".nynta_4326 as b
						WHERE a.ntacode = b.ntacode
						GROUP BY b.population_2016, a.ntacode,b.ntaname, a.${datasetDict[dataset]['groupby_cat']}
						ORDER BY ntaname,${datasetDict[dataset]['groupby_cat']}) as a ) as t
				WHERE t.rank<=5 ) as a,
			(SELECT a.ntacode,
					b.ntaname,
					count(*) count_nta,
					count(*)/b.population_2016 as perpop
				FROM "wxu-carto".${dataset} as a, "wxu-carto".nynta_4326 as b
				WHERE a.ntacode = b.ntacode GROUP BY b.population_2016, a.ntacode,b.ntaname) as b
            WHERE a.ntacode = b.ntacode and (${conditional})
```

acs_var_names = {
    "white_alone":"White alone",
    "black_alone":"Black alone",
    "asian_alone":"Asian alone",
    "native_american_alone":"Native American alone",
    "other_race_alone":"Other race alone",
    "hispanic_or_latino":"Hispanic or Latino",
    "non_family_households":"Non-family households",
    "family_households":"Family households",
    "total_population":"Total Population",
    "female":"Female",
    "male":"Male",
    "male_under_5_years":"Male, Under 5 years",
    "male_5_to_9_years":"Male, 5 to 9 years",
    "male_10_to_14_years":"Male, 10 to 14 years",
    "male_s_15_to_17_years":"Male,s 15 to 17 years",
    "male_18_and_19_years":"Male, 18 and 19 years",
    "male_20_years":"Male, 20 years",
    "male_21_years":"Male, 21 years",
    "male_22_to_24_years":"Male, 22 to 24 years",
    "male_25_to_29_years":"Male, 25 to 29 years",
    "male_30_to_34_years":"Male, 30 to 34 years",
    "male_35_to_39_years":"Male, 35 to 39 years",
    "male_40_to_44_years":"Male, 40 to 44 years",
    "male_45_to_49_years":"Male, 45 to 49 years",
    "male_50_to_54_years":"Male, 50 to 54 years",
    "male_55_to_59_years":"Male, 55 to 59 years",
    "male_60_and_61_years":"Male, 60 and 61 years",
    "male_62_to_64_years":"Male, 62 to 64 years",
    "male_65_and_66_years":"Male, 65 and 66 years",
    "male_67_to_69_years":"Male, 67 to 69 years",
    "male_70_to_74_years":"Male, 70 to 74 years",
    "male_75_to_79_years":"Male, 75 to 79 years",
    "male_80_to_84_years":"Male, 80 to 84 years",
    "male_85_years_and_over":"Male, 85 years and over",
    "female_under_5_years":"Female, Under 5 years",
    "female_5_to_9_years":"Female, 5 to 9 years",
    "female_10_to_14_years":"Female, 10 to 14 years",
    "female_15_to_17_years":"Female, 15 to 17 years",
    "female_18_and_19_years":"Female, 18 and 19 years",
    "female_20_years":"Female, 20 years",
    "female_21_years":"Female, 21 years",
    "female_22_to_24_years":"Female, 22 to 24 years",
    "female_25_to_29_years":"Female, 25 to 29 years",
    "female_30_to_34_years":"Female, 30 to 34 years",
    "female_35_to_39_years":"Female, 35 to 39 years",
    "female_40_to_44_years":"Female, 40 to 44 years",
    "female_45_to_49_years":"Female, 45 to 49 years",
    "female_50_to_54_years":"Female, 50 to 54 years",
    "female_55_to_59_years":"Female, 55 to 59 years",
    "female_60_and_61_years":"Female, 60 and 61 years",
    "female_62_to_64_years":"Female, 62 to 64 years",
    "female_65_and_66_years":"Female, 65 and 66 years",
    "female_67_to_69_years":"Female, 67 to 69 years",
    "female_70_to_74_years":"Female, 70 to 74 years",
    "female_75_to_79_years":"Female, 75 to 79 years",
    "female_80_to_84_years":"Female, 80 to 84 years",
    "female_85_years_and_over":"Female, 85 years and over",
    "less_than_10_000":"Less than $10,000",
    "_10_000_to_14_999":"$10,000 to $14,999",
    "_15_000_to_19_999":"$15,000 to $19,999",
    "_20_000_to_24_999":"$20,000 to $24,999",
    "_25_000_to_29_999":"$25,000 to $29,999",
    "_30_000_to_34_999":"$30,000 to $34,999",
    "_35_000_to_39_999":"$35,000 to $39,999",
    "_40_000_to_44_999":"$40,000 to $44,999",
    "_45_000_to_49_999":"$45,000 to $49,999",
    "_50_000_to_59_999":"$50,000 to $59,999",
    "_60_000_to_74_999":"$60,000 to $74,999",
    "_75_000_to_99_999":"$75,000 to $99,999",
    "_100_000_to_124_999":"$100,000 to $124,999",
    "_125_000_to_149_999":"$125,000 to $149,999",
    "_150_000_to_199_999":"$150,000 to $199,999",
    "_200_000_or_more":"$200,000 or more",
    "median_hh_income":"Median HH income",
    "regular_high_school_diploma":"Regular high school diploma",
    "ged_or_alternative_credential":"GED or alternative credential",
    "some_college_less_than_1_year":"Some college, less than 1 year",
    "some_college_1_or_more_years_":"Some college, 1 or more years,",
    "associate_s_degree":"Associate's degree",
    "bachelor_s_degree":"Bachelor's degree",
    "master_s_degree":"Master's degree",
    "professional_school_degree":"Professional school degree",
    "doctorate_degree":"Doctorate degree",
}